'use strict';

module.exports = function(verb) {
  verb.use(require('verb-generate-readme'));
  verb.generator('generator', require('./'));

  verb.helper('fileList', function(name) {
    var gen = this.app.getGenerator('generator');
    var deps = this.app.pkg.get('dependencies');
    var list = '';

    gen.tasks[name || 'files'].deps.forEach(function(key) {
      var match = matchDep(deps, key);
      list += `- \`` + key + `\`${match ? `: generated by [${match}][]` : ''}\n`;
    });
    return list;
  });

  verb.task('docs', ['setup', 'templates'], function() {
    return verb.src('docs/src/*.md')
      .pipe(verb.renderFile('*'))
      .pipe(verb.dest('docs'));
  });

  verb.task('default', ['readme']);
};

function matchDep(deps, key) {
  var keys = Object.keys(deps);
  var len = keys.length;
  var idx = -1;
  while (++idx < len) {
    var dep = keys[idx];
    var match = /^generate-(.*)/.exec(dep);
    if (!match) continue;
    var name = match[1];
    if (key.indexOf(name) === 0) {
      return dep;
    }
  }
  return null;
}
